# Generated by Django 2.2.7 on 2019-11-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20191128_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
    ]
