# Generated by Django 2.2.7 on 2019-12-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_saloon_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
