# Generated by Django 3.0 on 2019-12-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_appointment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='employees_number',
            field=models.IntegerField(verbose_name='Количество сотрудников'),
            preserve_default=False,
        ),
    ]
